language: node_js

node_js:
  - 'node'

cache:
  directories:
    - 'node_modules'

script:
  - yarn
  - yarn lint
  - yarn global add @quasar/cli
  - quasar build --mode electron --target linux

deploy:
  provider: releases
  api_key: $GITHUB_AUTH_TOKEN
  file_glob: true
  file:
    - dist/electron/Packaged/*.AppImage
    - dist/electron/Packaged/*.snap
  skip_cleanup: true
  on:
    tags: true
